language: python
dist: focal
install:
  - pip3 install --upgrade pip
  - pip3 install -U pytest pylibacl evdev setuptools
  - python setup.py build
  - python setup.py install
script: PYTHONPATH=. py.test
# needed by pylibacl
addons:
  apt:
    packages:
      - libacl1-dev
      - libusb-1.0-0-dev
