language: python
dist: focal
install:
  - pip3 install --upgrade pip
  - pip3 install -U libusb1 setuptools
  - python setup.py build
  - python setup.py install
script: sc-xbox.py start
# needed by pylibacl
addons:
  apt:
    packages:
      - libusb-1.0-0-dev
